TOOLS_DIR?=../tools
TARGET=colorlight_5a_75e#TARGET: placa de desarrollo
GATEWARE=base#GATEWARE: base.py el cual representa el gateware
# OPENFPGALOADER_BOARD=
GATE_DIR=build/${TARGET}/gateware
SOFT_DIR=build/${TARGET}/software
include ../tools/Makefile
